# Generated by Django 4.1.3 on 2022-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('CreditNote', 'CN'), ('ElectronicBill', 'EB')], max_length=20)),
            ],
        ),
    ]
