# Generated by Django 4.1.3 on 2022-12-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_trackdocument_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackdocument',
            name='foto',
        ),
    ]
